### ISSUE TITLE
Bump to 4.1.4

### ISSUE THREAD

**Issue by Pattern-Projects** [HalBuilder/halbuilder-standard#7]
Is it possible to bump this up to include halbuilder-xml:4.1.4 on maven central?

**Comment by talios** [comment]
Sure - for now, you can just add a direct dependency on `halbuilder-xml`.  We generally exclude all transitives and declare things directly, sorry for missing that - I'll get that updated tonight.

**Comment by talios** [comment]
That should be in Maven Central by now - was released shortly after that last comment.  halbuiler-standard:4.1.2

**Comment by Pattern-Projects** [comment]
That's great. Thank you!
